from __future__ import annotations

import json
import os
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/worklens-matplotlib")

import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
MODEL_DIR = ROOT / "models"
REPORT_DIR = ROOT / "reports"


def load_metrics(name: str) -> dict:
    path = MODEL_DIR / f"{name}_metrics.json"
    if not path.exists():
        raise FileNotFoundError(f"Missing {path}. Run `make train` first.")
    return json.loads(path.read_text())


def main() -> None:
    sla = load_metrics("sla_breach_model")
    completion = load_metrics("completion_time_model")
    early_anomaly = load_metrics("anomaly_model")
    retrospective_anomaly = load_metrics("retrospective_anomaly_model")
    sla_test = sla["models"][sla["selected_model"]]
    completion_test = completion["models"][completion["selected_model"]]

    figure_dir = REPORT_DIR / "synthetic_figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    calibration = sla["calibration_curve"]
    plt.plot(
        calibration["mean_predicted_probability"],
        calibration["fraction_positive"],
        marker="o",
        label=sla["selected_model"],
    )
    plt.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Ideal")
    plt.xlabel("Mean predicted probability")
    plt.ylabel("Observed synthetic breach rate")
    plt.legend()
    plt.tight_layout()
    plt.savefig(figure_dir / "sla_calibration.png", dpi=160)
    plt.close()

    model_names = list(completion["models"])
    mae = [completion["models"][name]["mae"] for name in model_names]
    plt.barh(model_names, mae, color="#295c49")
    plt.xlabel("Temporal holdout MAE (hours)")
    plt.tight_layout()
    plt.savefig(figure_dir / "completion_model_comparison.png", dpi=160)
    plt.close()

    REPORT_DIR.mkdir(exist_ok=True)
    (REPORT_DIR / "synthetic_model_report.md").write_text(
        f"""# Synthetic product-demo model report

Generated by `scripts/generate_synthetic_model_report.py` from saved metrics
created by `python -m src.ml.train_all`.

## SLA breach classification

- Selected model: {sla["selected_model"]}
- Primary validation: {sla["validation_strategy"]}
- ROC-AUC: {sla_test["roc_auc"]:.4f}
- PR-AUC: {sla_test["pr_auc"]:.4f}
- Precision: {sla_test["precision"]:.4f}
- Recall: {sla_test["recall"]:.4f}
- F1: {sla_test["f1"]:.4f}
- Brier score: {sla_test["brier_score"]:.4f}
- Operating threshold: {sla_test["decision_threshold"]:.2f}

## Completion-time regression

- Selected model: {completion["selected_model"]}
- MAE: {completion_test["mae"]:.2f} hours
- RMSE: {completion_test["rmse"]:.2f} hours
- Median absolute error: {completion["selected_test_median_absolute_error"]:.2f} hours
- R²: {completion_test["r2"]:.4f}
- Median-baseline MAE: {completion["models"]["Median Baseline"]["mae"]:.2f} hours

## Anomaly modes

- Early anomaly risk: {early_anomaly["flagged_cases"]:,} cases at a
  {early_anomaly["threshold"]:.4f} threshold, using prefix-safe fields.
- Retrospective investigation: {retrospective_anomaly["flagged_cases"]:,} cases at a
  {retrospective_anomaly["threshold"]:.4f} threshold, using completed-case fields.

## Evidence boundary

All results in this report use deterministic synthetic healthcare-claims data.
They demonstrate product and engineering behavior. They are not evidence of
performance on real claims, clinical, fraud, or payment decisions.
"""
    )
    print("Generated synthetic model report from saved metrics")


if __name__ == "__main__":
    main()
