from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.ml.feature_registry import feature_registry_frame


def main() -> None:
    frame = feature_registry_frame()
    reports = Path("reports")
    reports.mkdir(exist_ok=True)
    frame.to_csv(reports / "leakage_audit.csv", index=False)

    docs = Path("docs")
    docs.mkdir(exist_ok=True)
    columns = [
        "feature_name",
        "feature_group",
        "available_at_prediction_time",
        "prediction_stage",
        "uses_future_information",
        "safe_for_sla_prediction",
        "safe_for_remaining_time_prediction",
        "safe_for_early_anomaly_detection",
        "safe_for_retrospective_analysis",
        "notes",
    ]
    selected = frame[columns].astype(str)
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    rows = [
        "| " + " | ".join(value.replace("|", "\\|") for value in row) + " |"
        for row in selected.itertuples(index=False, name=None)
    ]
    table = "\n".join([header, divider, *rows])
    (docs / "leakage_audit.md").write_text(
        "# Leakage audit\n\n"
        "Generated by `scripts/generate_leakage_audit.py`. Early-model training "
        "fails when an unregistered or unsafe feature is supplied.\n\n" + table + "\n"
    )
    print(f"Audited {len(frame)} registered features")


if __name__ == "__main__":
    main()
